name: Stormworx notification workflow

on:
  schedule:
    - cron: "0 18 * * 1-7"
  workflow_call:
  workflow_dispatch:

env:
  STORMWORX_EMAIL: ${{ secrets.STORMWORX_EMAIL }}
  STORMWORX_PASSWORD: ${{ secrets.STORMWORX_PASSWORD }}
  STORMWORX_SMTP: ${{ secrets.STORMWORX_SMTP }}
  STORMWORX_SMTP_PORT: ${{ secrets.STORMWORX_SMTP_PORT }}
  OPENWEATHER_APP_ID: ${{ secrets.OPENWEATHER_APP_ID }}
  MARIADB_URL: ${{ secrets.MARIADB_URL }}
  MARIADB_USERNAME: ${{ secrets.MARIADB_USERNAME }}
  MARIADB_PASSWORD: ${{ secrets.MARIADB_PASSWORD }}
  SECRET_EMAIL: ${{ secrets.SECRET_EMAIL }}

jobs:
  execution:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
      - name: Run App
        run: nohup ./runApp.sh  > build.log 2>&1 < /dev/null &
      - name: Sleep for 2 minutes
        run: sleep 120s
        shell: bash
      - name: Send notification
        run: ./sendNotification.sh
