name: Stormworx notification workflow

on:
  workflow_call:
  workflow_dispatch:

env:
  STORMWORX_EMAIL: ${{ secrets.STORMWORX_EMAIL }}
  STORMWORX_PASSWORD: ${{ secrets.STORMWORX_PASSWORD }}
  STORMWORX_SMTP: ${{ secrets.STORMWORX_SMTP }}
  STORMWORX_SMTP_PORT: ${{ secrets.STORMWORX_SMTP_PORT }}
  OPENWEATHER_APP_ID: ${{ secrets.OPENWEATHER_APP_ID }}

jobs:
  execution:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build